#!/bin/bash
module purge > /dev/null 2>&1
module load testing > /dev/null 2>&1
module load openmpi/2.0.0/gnu/6.2.0 > /dev/null 2>&1
mpicc -Ofast -flto -march=native "$@"
module purge > /dev/null 2>&1
