#!/bin/bash
module purge > /dev/null 2>&1
module load testing > /dev/null 2>&1
module load openmpi/2.1.1/intel/17.0/cuda/7.5 > /dev/null 2>&1
mpiicc -xHost -ipo -Ofast -vec "$@"
module purge > /dev/null 2>&1
